# =======================================
# ⚠️ 이 파일은 더 이상 사용되지 않습니다
# config/_default/config.toml 사용 (공통 설정)
# config/development/config.toml 사용 (개발 환경)
# config/production/config.toml 사용 (배포 환경)
# =======================================
#
# 이 파일을 삭제해도 되지만, 참고용으로 남겨둡니다.
# Hugo는 config/ 디렉토리가 있으면 이 파일을 무시합니다.