baseURL = "http://localhost:1313/"
title = "Apptest.ai Docs"
theme = "hugo-book"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true   # ko도 /ko/ 아래로

# 기본 설정
enableRobotsTXT = true
enableGitInfo = true              # Git 커밋 정보 기반 lastmod 자동화
canonifyURLs = true               # 절대 URL로 변환
enableEmoji = true                # 이모지 지원 (:smile: 등)

[params]
  BookTheme = "auto"
  BookSearch = true               # 검색 기능 활성화
  BookToC = true                  # 우측 목차(ToC) 표시
  # 공통값이 있으면 여기, 언어별 값은 [languages.xx.params]에서 override

# ── 언어별 설정
[languages]

  [languages.ko]
    languageName = "한국어"
    weight = 1
    title = "Apptest.ai 문서"
    contentDir = "content/ko"        # ← 언어별 콘텐츠 루트
    [languages.ko.params]
      BookSection = "docs"           # 사이드바에 사용할 섹션 폴더명
      BookDateFormat = "2006-01-02"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Apptest.ai Docs"
    contentDir = "content/en"
    [languages.en.params]
      BookSection = "docs"
      BookDateFormat = "Jan 2, 2006"

# (선택) 언어별 메뉴 예시
[menus]
  # 공통 메뉴가 필요하면 여기
[languages.ko.menus]
  [[languages.ko.menus.after]]
    name = "Apptest.ai"
    url  = "https://apptest.ai"
    weight = 10
[languages.en.menus]
  [[languages.en.menus.after]]
    name = "Apptest.ai"
    url  = "https://apptest.ai"
    weight = 10