# =======================================
# Netlify Configuration (OAuth 전용)
# =======================================
# 이 설정은 Decap CMS OAuth 인증만 제공합니다.
# 실제 사이트는 GitHub Pages에서 호스팅됩니다.

# Hugo 빌드 설정
[build]
  publish = "public"
  command = "hugo --environment production --minify"

[build.environment]
  HUGO_VERSION = "0.140.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

