# =======================================
# 개발 환경 설정
# hugo server 실행 시 자동 적용
# =======================================
baseURL = "http://localhost:1313/"

# 개발 환경 전용 설정
buildDrafts = true                # draft 문서도 표시
buildFuture = true                # 미래 날짜 문서도 표시

