# =======================================
# 프로덕션 환경 설정
# hugo --environment production 실행 시 적용
# =======================================
# GitHub Pages URL (저장소명에 맞게 수정 필요)
baseURL = "https://apptestai.github.io/docs-new/"

# 프로덕션 환경 전용 설정
buildDrafts = false               # draft 문서 제외
buildFuture = false               # 미래 날짜 문서 제외
minify = true                     # HTML/CSS/JS 압축

