name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때마다 자동 배포

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true        # 테마(hugo-book) 서브모듈 포함
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.149.0'   # or 'latest'
          extended: true          # SCSS 사용 시 필수

      - name: Build
        run: hugo --minify        # public 폴더 생성

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
